version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'
        
services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: gva-web
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - server
    command: [ 'nginx-debug', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: gva-server
    restart: always
    ports:
      - '8889:8888'
    depends_on:
      - chromedp-headless-shell
    networks:
      network:
        ipv4_address: 177.7.0.12
  
  chromedp-headless-shell:
    build:
        context: ./chromedp-headless-shell
        dockerfile: ./Dockerfile
    container_name: chromedp-headless-shell
    restart: always
    ports:
      - '9222:9222'
    networks:
      network:
        ipv4_address: 177.7.0.13