version: "3"    
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    restart: always
    volumes:
      - ./server/config.docker.yaml:/data/app/goadmin/config.docker.yaml
      - ./server/log:/data/app/goadmin/log
    ports:
      - '8989:8989'
    depends_on:
      - chromedp-headless-shell
    networks:
      network:
        ipv4_address: 177.7.0.12
  
  chromedp-headless-shell:
    build:
        context: ./tools/chromedp-headless-shell
        dockerfile: ./Dockerfile
    container_name: chromedp-headless-shell
    restart: always
    ports:
      - '9222:9222'
    networks:
      network:
        ipv4_address: 177.7.0.13
# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'