package {{ .PackageName }}

type ApiGroup struct {
	// Code generated by github.com/liujianjiang/goadmin/server Begin; DO NOT EDIT.

	// Code generated by github.com/liujianjiang/goadmin/server End; DO NOT EDIT.
}
